### ISSUE TITLE
没有办法install这个库,是我的源或者Python版本不对吗

### ISSUE THREAD

**Issue by dyjae** [PyQt5/PyQtWebKit#1]
你好,我没有办法install这个库.

![image](https://user-images.githubusercontent.com/10864799/95593629-847dee00-0a7c-11eb-8f6f-5b965ad6821b.png)

pip  版本 20.2.3 
python 版本 3.8
源试了阿里和原生的都不行

**Comment by 892768447** [comment]
由于webkit已经不在qt后续的版本里了。这里只是做了一个windows版本的编译。目前版本是5.13.1
https://pypi.org/project/PyQtWebKit/#files

也就是说只支持windows  python 35 36 37版本的pyqt5.13.1版本
![image](https://user-images.githubusercontent.com/5131669/95599911-497fb880-0a84-11eb-8597-d1021a7ac972.png)

**Comment by wangyexiang** [comment]
> 也就是说只支持windows python 35 36 37版本的pyqt5.13.1版本 !
也就是说python 3.8，3.9都不能用？我用python3.9，报错：
`ImportError: DLL load failed while importing QtWebKitWidgets: 找不到指定的模块。`

**Comment by 892768447** [comment]
> > 也就是说只支持windows python 35 36 37版本的pyqt5.13.1版本 !
> > 也就是说python 3.8，3.9都不能用？我用python3.9，报错：
> > `ImportError: DLL load failed while importing QtWebKitWidgets: 找不到指定的模块。`

是的，而且不推荐使用该库，建议还是切换为 QWebEngineView

**Comment by vmtest888** [comment]
> > 也就是说只支持windows python 35 36 37版本的pyqt5.13.1版本 !
> > 也就是说python 3.8，3.9都不能用？我用python3.9，报错：
> > `ImportError: DLL load failed while importing QtWebKitWidgets: 找不到指定的模块。`

我3.8调用成功。    但是可惜没有mac和linux版本

**Comment by 892768447** [comment]
可以参考项目的编译脚本自行编译，另外mac的这里有文章
https://pyqt5.com/pyqtclientmac.html

**Comment by vmtest888** [comment]
https://github.com/qtwebkit/qtwebkit/releases

似乎qtwebkit 2020年又发布了一个，大佬方便的话可以更新一下了。
